import { InjectQueue } from '@nestjs/bullmq';
import { Injectable, Logger } from '@nestjs/common';
import { ERROR_CODES, type UserProfile } from '@gemone/contracts';
import { Queue } from 'bullmq';

import { PrismaService } from '../../core/database/prisma.service';
import { DomainError } from '../../core/errors/app-error';
import {
  NOTIFICATION_JOBS,
  QUEUES,
  type PasswordResetEmailJobData,
  type VerificationEmailJobData,
} from '../../core/queue/queue.constants';
import { UsersService } from '../users/users.service';
import { REVOCATION_REASONS } from './auth.constants';
import { LoginThrottleService } from './login-throttle.service';
import { PasswordService } from './password.service';
import { VerificationService } from './verification.service';
import { type IssuedSession, type SessionContext, TokenService } from './token.service';

export interface AuthResult {
  user: UserProfile;
  session: IssuedSession;
}

/**
 * Registration and login — ARCHITECTURE.md §8.
 *
 * Email and password only (§8.0). Session issuance is deliberately separate
 * from credential verification, so adding a second factor or an OAuth
 * provider later slots between the two steps without restructuring anything
 * that calls this service (§8.4).
 */
@Injectable()
export class AuthService {
  private readonly logger = new Logger(AuthService.name);

  constructor(
    private readonly users: UsersService,
    private readonly passwords: PasswordService,
    private readonly tokens: TokenService,
    private readonly throttle: LoginThrottleService,
    private readonly verification: VerificationService,
    private readonly prisma: PrismaService,
    @InjectQueue(QUEUES.NOTIFICATIONS) private readonly notifications: Queue,
  ) {}

  async register(
    email: string,
    password: string,
    context: SessionContext = {},
  ): Promise<AuthResult> {
    // Policy is checked before hashing: hashing a password we are going to
    // reject spends ~19 MiB and real CPU on nothing, which is a free
    // denial-of-service for anyone posting long invalid passwords.
    this.passwords.assertMeetsPolicy(password);

    const passwordHash = await this.passwords.hash(password);

    const user = await this.users.create({
      email,
      passwordHash,
      registrationIp: context.ip,
    });

    this.logger.log({ userId: user.id }, 'User registered');

    await this.sendVerificationEmail(user.id, user.email);

    const session = await this.tokens.issueSession(user.id, user.role, context);

    // Registering logs you in. Requiring a separate login immediately after
    // is friction with no security benefit — the credentials were just
    // proven, in this request.
    return { user: UsersService.toProfile(user), session };
  }

  async login(
    email: string,
    password: string,
    context: SessionContext = {},
  ): Promise<AuthResult> {
    /*
     * The throttle takes this attempt's place before anything expensive —
     * §8.3, TODO T2.
     *
     * Before the lookup and before argon2, because verifying a password is the
     * costliest thing on this path and a guessing attack that pays for one on
     * every request is a CPU exhaustion vector as well as a credential one.
     * And because a check that reads the counter here but writes it after the
     * verdict is a check every concurrent request passes: the increment has to
     * happen on this line for the ceiling to mean anything.
     *
     * The bucket is derived from the *email*, never from a user id: an address
     * with no account must throttle exactly like one with an account, or the
     * lockout itself answers the question the shared error code and the decoy
     * verification below exist to refuse.
     */
    const accountKey = LoginThrottleService.accountKeyFor(email);
    const ip = context.ip ?? null;

    await this.throttle.reserveAttempt(accountKey, ip);

    const user = await this.users.findByEmail(email);

    if (!user) {
      // Verify against a decoy anyway, so a request for an unknown email
      // costs what one for a known email costs. Without it, response timing
      // tells an attacker which addresses are registered — the exact thing
      // the shared error code exists to hide. The decoy is generated by
      // PasswordService from its own parameters; a literal written here is
      // how this equaliser silently stopped working once already.
      await this.passwords.verifyDecoy(password);
      throw invalidCredentials();
    }

    const passwordMatches = await this.passwords.verify(user.passwordHash, password);
    if (!passwordMatches) {
      this.logger.log({ userId: user.id }, 'Failed login attempt');
      throw invalidCredentials();
    }

    /*
     * The password verified, so this attempt gives back what it reserved —
     * here rather than after the status check below, because what earns the
     * release is a correct credential and not a completed login.
     *
     * The account count goes entirely; the address count goes down by this
     * attempt alone and keeps every failure that came before it — see D73.
     */
    await this.throttle.releaseAttempt(accountKey, ip);

    if (!UsersService.isActive(user)) {
      // Checked after the password, deliberately: answering "this account is
      // suspended" to anyone who guesses an email address confirms the
      // address exists and leaks its state.
      this.logger.warn(
        { userId: user.id, status: user.status },
        'Login attempt on an inactive account',
      );
      throw new DomainError(
        ERROR_CODES.AUTH_ACCOUNT_INACTIVE,
        'This account is not active',
        403,
      );
    }

    this.logger.log({ userId: user.id }, 'User logged in');

    const session = await this.tokens.issueSession(user.id, user.role, context);

    return { user: UsersService.toProfile(user), session };
  }

  /** Spends a verification token — ARCHITECTURE.md §8.3. */
  async verifyEmail(token: string): Promise<void> {
    await this.verification.confirmEmail(token);
  }

  /**
   * Starts a password reset — ARCHITECTURE.md §8.3.
   *
   * **Returns nothing, and returns it the same way every time.** §8.3 requires
   * that this endpoint not reveal whether an address has an account, and the
   * only way to keep that promise is for the caller-visible outcome to be
   * independent of everything decided below: unknown address, suspended
   * account, and a queue that refused the job all end here identically.
   *
   * Unlike login, no decoy work is needed to make the timings match. Nothing on
   * this path is expensive enough to measure — there is no argon2 verification
   * here, only a lookup and an enqueue.
   */
  async requestPasswordReset(email: string): Promise<void> {
    const user = await this.users.findByEmail(email);

    if (!user) {
      // Logged, because a burst of these against addresses that do not exist
      // is what an enumeration attempt looks like from the inside — the one
      // place it is still visible after the response has been equalised.
      this.logger.log('Password reset requested for an unknown address');
      return;
    }

    if (!UsersService.isActive(user)) {
      // A banned account's password is not worth resetting: login refuses it
      // whatever the password is, so the email would be an invitation to
      // nothing. Suspended accounts are treated the same, deliberately —
      // whether that changes is a policy decision, not this feature's.
      this.logger.warn(
        { userId: user.id, status: user.status },
        'Password reset requested for an inactive account',
      );
      return;
    }

    try {
      const token = await this.verification.issuePasswordReset(user.id);

      const data: PasswordResetEmailJobData = { userId: user.id, email: user.email, token };
      await this.notifications.add(NOTIFICATION_JOBS.PASSWORD_RESET_EMAIL, data);

      this.logger.log({ userId: user.id }, 'Password reset email queued');
    } catch (error) {
      // Swallowed for the reason above: an error here would answer the
      // question the equal response exists to refuse, and it would answer it
      // for exactly the addresses that do have accounts.
      this.logger.error(
        { userId: user.id, err: error instanceof Error ? error.message : String(error) },
        'Could not queue the password reset email',
      );
    }
  }

  /**
   * Spends a reset token and sets a new password — ARCHITECTURE.md §8.2, §8.3.
   *
   * The three writes are one transaction. A reset that set the password but
   * left the sessions alive would leave whoever prompted the reset still
   * logged in, which is the specific outcome the user was trying to produce by
   * resetting; and one that spent the token without setting the password would
   * consume the only link they have.
   */
  async resetPassword(token: string, newPassword: string): Promise<void> {
    // Before the transaction, and before hashing — the policy check is free
    // and argon2 is not, and neither should be holding row locks while the
    // other runs.
    this.passwords.assertMeetsPolicy(newPassword);

    const passwordHash = await this.passwords.hash(newPassword);

    const userId = await this.prisma.$transaction(async (tx) => {
      const owner = await this.verification.consumePasswordReset(token, tx);

      await this.users.updatePasswordHash(owner, passwordHash, tx);
      await this.tokens.revokeAllForUser(owner, REVOCATION_REASONS.PASSWORD_RESET, tx);

      return owner;
    });

    this.logger.log({ userId }, 'Password reset completed');
  }

  /**
   * Issues a verification token and queues its delivery.
   *
   * **Neither step fails registration.** The account exists, its balance
   * exists, and the session has been issued; nothing about this platform is
   * withheld from an unverified address today. Turning a Redis blip into a
   * failed signup would trade a working account for an unsent email, and the
   * caller has already been told they are registered by the time delivery is
   * attempted anyway — it happens on a queue precisely so the request does not
   * wait for it.
   */
  private async sendVerificationEmail(userId: string, email: string): Promise<void> {
    try {
      const token = await this.verification.issueEmailVerification(userId);

      const data: VerificationEmailJobData = { userId, email, token };
      await this.notifications.add(NOTIFICATION_JOBS.VERIFICATION_EMAIL, data);
    } catch (error) {
      this.logger.error(
        { userId, err: error instanceof Error ? error.message : String(error) },
        'Could not queue the verification email; the account exists but is unverified',
      );
    }
  }

  async refresh(refreshToken: string, context: SessionContext = {}): Promise<AuthResult> {
    const { userId, session } = await this.tokens.rotate(refreshToken, context);

    const user = await this.users.findById(userId);
    if (!user) {
      // The foreign key makes this unreachable; treating it as an error
      // rather than an assertion means a future schema change cannot turn it
      // into a session for a user who no longer exists.
      throw invalidCredentials();
    }

    return { user: UsersService.toProfile(user), session };
  }

  async logout(refreshToken: string | undefined): Promise<void> {
    if (!refreshToken) return;
    await this.tokens.revokeByToken(refreshToken);
  }
}

function invalidCredentials(): DomainError {
  // One code for "no such email" and "wrong password". Distinguishing them
  // turns the login endpoint into an account-enumeration oracle.
  return new DomainError(
    ERROR_CODES.AUTH_INVALID_CREDENTIALS,
    'Invalid email or password',
    401,
  );
}
